```{r}
#| results: "asis"
#| echo: false

source("_common.R")
load("./data/dat0_0118.RData")  # dat0, spec4matrix

```

# Protein Data {#sec-protein-analysis}

## EVV Data   {#sec-protein-evv-analysis}

```{r}
#| label: fig-heatmap-protein-evv-wk6
#| echo: false
#| fig-cap: |
#|   Heatmap Representation of Protein EVV Biodistribution Data Measured at Interim Necropsy Week 6.
#| fig-cap-location: top
#| fig-alt: |
#|   A heatmap Representation of RNA Biodistribution Data Measured at Interim Necropsy Week 6.  
#| fig-width: 8
#| fig-height: 15 


# 3003        3     1 Brain, White Matter  4368 <NA>   LPA     132.76                NA WM       BR           6 Low + IS Male  Terminal Necropsy Weeks 26/27


PARAMCD_filter = "EVV" 

df = dat0 %>% filter(!GROUP %in% c(1, 2))

biodist_value <- df  %>% 
  filter(
    PARAMCD %in% PARAMCD_filter 
  ) %>% 
  pull(AVAL) %>% as.numeric() %>% log10()

biodist_min <- min(biodist_value, na.rm=TRUE) 
biodist_max <- max(biodist_value, na.rm=TRUE)
biodist_median <- median(biodist_value, na.rm=TRUE)
col_scheme = colorRamp2(c(biodist_min, biodist_median, biodist_max), c("blue", "white", "red"))
 
ht1 = create_heatmap(
  data = df, 
  col_scheme = col_scheme,
  ATPT_f_filter = "Interim Necropsy Week 6",  # "Interim Necropsy Week 6"  
  PARAMCD_filter = PARAMCD_filter,   # "PK"       "VGC_MTH1" "VGC_MTH2" "RNA_MTH1" "RNA_MTH2" "EVV"      "LPA" 
  scale_data = FALSE,           # Whether to scale the data
  na_threshold = 0.5,          # NA threshold to filter
  cluster_rows = FALSE,         # Whether to cluster rows
  cluster_columns = TRUE       # Whether to cluster columns
) 

ht2 = create_heatmap(
  data = df, #  %>% mutate(MATRIXCD = ordered(MATRIXCD, levels=tmp1$colnames_lst)) %>% dplyr::arrange(MATRIXCD), 
  col_scheme = col_scheme,
  ATPT_f_filter = "Terminal Necropsy Weeks 26/27",  # "Interim Necropsy Week 6"  
  PARAMCD_filter = PARAMCD_filter,   # "PK"       "VGC_MTH1" "VGC_MTH2" "RNA_MTH1" "RNA_MTH2" "EVV"      "LPA" 
  scale_data = FALSE,           # Whether to scale the data
  na_threshold = 0.5,          # NA threshold to filter
  cluster_rows = FALSE, #  function(df) as.dendrogram(row_dend(ht2)), # (ComplexHeatmap::row_dend(ht2)),         # Whether to cluster rows
  cluster_columns = TRUE #   function(df) as.dendrogram(column_dend(ht2))       # Whether to cluster columns
)

draw(ht1, padding = unit(c(0.5, 0.5, 0.5, 0.5), "mm"), merge_legend = TRUE) # Adjust padding

```

```{r}
#| label: fig-heatmap-protein-evv-wk26
#| echo: false
#| fig-cap: |
#|   Heatmap Representation of Protein EVV Biodistribution Data Measured at Terminal Necropsy Weeks 26/27.
#| fig-cap-location: top
#| fig-alt: |
#|   A heatmap Representation of RNA Biodistribution Data Measured at Terminal Necropsy Weeks 26/27.  
#| fig-width: 8
#| fig-height: 15 
 

draw(ht2, padding = unit(c(0.5, 0.5, 0.5, 0.5), "mm"), merge_legend = TRUE) # Adjust padding


# note for all biological matrix
a_matrix_lst <- dat0 %>% filter(!GROUP %in% c(1, 2))  %>% 
  dplyr::filter(
    PARAMCD %in% PARAMCD_filter  # , ATPT_f %in% ATPT_f_filter
  ) %>%  
  pull(MATRIX)  %>% unique()

abbreviation_of_matrix_lst <- spec4matrix %>%
  dplyr::filter(MATRIX %in% a_matrix_lst) %>% 
  dplyr::arrange(MATRIXCD) %>% 
  tidyr::unite("ABBR", MATRIXCD, MATRIX, sep = " = ") %>% 
  dplyr::pull(ABBR) %>% paste0( collapse="; ")   

```

::: {style="color: gray; font-size: 0.8em;"}
Note, `r abbreviation_of_matrix_lst`.
:::

## Correlation analysis {#sec-protein-correlation-analysis}

```{r}
#| label: fig-protein-VGC-correlation-scatterplot
#| echo: false
#| fig-cap: |
#|   Scatterplot of Protein vs VGC Biodistribution Data, Colored by Treatment Group, Faceted by Biological Matrix in Study xxxx.  
#| fig-cap-location: top
#| fig-alt: |
#|   A heatmap showing the distribution of VGC data Across Treatment Group, Faceted by Biological Matrix in Study xxxx. 
#| fig-width: 8
#| fig-height: 15


# Question:  How is the correlation between the protein EVV data with the VGC data at both timepoints (interim necropsy week 6 and week 26/27?
 
df = dat0 %>% 
  filter(!GROUP %in% c(1,2)) %>% 
  filter(TISSUE=="Brain", PARAMCD %in% c("VGC_MTH1", "EVV")) %>% 
  mutate(AVAL = as.numeric(AVAL)) %>%
  pivot_wider(
      id_cols = c("USUBJID", "ATPT_f", "GROUP_f", "MATRIX"), 
      names_from = c("PARAMCD"),
      values_from = "AVAL"
  )
 
library(ggplot2)
library(ggpubr)

create_scatter_correlation_plot <- function(df, x, y, group, shape, facet) {
   # Convert string column names to symbols for tidy evaluation
  x <- sym(x)
  y <- sym(y)
  
  # Filter out rows where either x or y is NA
  df <- df %>% filter(!is.na(!!x) & !is.na(!!y))
  
  ggplot(data = df,  
         aes_string(x = x, y = y)) +  
    geom_point(aes_string(group = "USUBJID", color = group, shape = shape), size = 2) +  
    ggpubr::stat_cor(aes(label = after_stat(rr.label)), label.x = 100, label.y = 250, color = "black", linewidth = 1.0, size = 2.5) +
    geom_smooth(method = "lm", se = TRUE, color = "black", show.legend = FALSE,
                color = "gray30", fill = "gray70", size = 0.7, fullrange = TRUE) +  
    # scale_x_continuous("Brain Human LPA peptide (ng/mL)") +
    # scale_y_continuous("Delta4 (ng/mL)") +
    # geom_hline(yintercept = 1.95, linetype = 2) +  
    labs(title = paste0(y, " vs ", x, 
                        " (Colored by ", group, 
                        ", Shaped by ", shape,
                        ", Faceted by ", facet, 
                        ")") 
         #caption = paste("Animal 6001 removed due to high predose NAb titer.")
         ) +
    facet_wrap(as.formula(paste("~", facet)), scales = "free") +  
    theme_prism2(base_size = 7) +
    scale_shape_manual(values = c(21, 4, 1)) +  
    #scale_color_manual(values = as.vector(glasbey(20))) +
    theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust = 1)) 
}

# Calling the function with the specified parameters
create_scatter_correlation_plot(df, "VGC_MTH1", "EVV", "GROUP_f", "ATPT_f", "MATRIX")

```

```{r}
#| label: fig-protein-RNA-correlation-scatterplot
#| echo: false
#| fig-cap: |
#|   Scatterplot of Protein vs RNA Biodistribution Data, Colored by Treatment Group, Faceted by Biological Matrix in Study xxxx.  
#| fig-cap-location: top
#| fig-alt: |
#|   A heatmap showing the distribution of VGC data Across Treatment Group, Faceted by Biological Matrix in Study xxxx. 
#| fig-width: 8
#| fig-height: 15


# Question:  How is the correlation between the protein EVV data with the RNA data at both timepoints (interim necropsy week 6 and week 26/27?
 
df = dat0 %>% 
  filter(!GROUP %in% c(1,2)) %>% 
  filter(TISSUE=="Brain", PARAMCD %in% c("RNA_MTH1", "EVV")) %>% 
  mutate(AVAL = as.numeric(AVAL)) %>%
  pivot_wider(
      id_cols = c("USUBJID", "ATPT_f", "GROUP_f", "MATRIX"), 
      names_from = c("PARAMCD"),
      values_from = "AVAL"
  )
 
library(ggplot2)
library(ggpubr)
 

# Calling the function with the specified parameters
create_scatter_correlation_plot(df, "RNA_MTH1", "EVV", "GROUP_f", "ATPT_f", "MATRIX")

```